apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: psql
      image: postgres:17
      command:
        - sleep
        - "3600"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
