"""add unique constraint to place name

Revision ID: 2c098ed82832
Revises: 2648be1f75f2
Create Date: 2026-07-17 09:22:22.662672

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c098ed82832"
down_revision: Union[str, Sequence[str], None] = "2648be1f75f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "places", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "places", type_="unique")
    # ### end Alembic commands ###
