"""change event status to enum

Revision ID: 9038ddd58d07
Revises: 2cce39d398fe
Create Date: 2026-08-02 14:05:51.372028

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9038ddd58d07"
down_revision: Union[str, Sequence[str], None] = "2cce39d398fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_status = sa.Enum(
        "new",
        "published",
        "registration_closed",
        "finished",
        name="eventstatus",
    )

    event_status.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "events",
        "status",
        existing_type=sa.VARCHAR(length=255),
        type_=event_status,
        existing_nullable=False,
        postgresql_using="status::eventstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_status = sa.Enum(
        "new",
        "published",
        "registration_closed",
        "finished",
        name="eventstatus",
    )

    op.alter_column(
        "events",
        "status",
        existing_type=event_status,
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )

    event_status.drop(op.get_bind(), checkfirst=True)


# ### end Alembic commands ###
