"""add sync metadata table

Revision ID: c62f15790944
Revises: e8ac9e966191
Create Date: 2026-07-24 16:27:46.633051

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c62f15790944"
down_revision: Union[str, Sequence[str], None] = "e8ac9e966191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("last_sync_time", sa.DateTime(), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "sync_status",
            sa.Enum("PENDING", "RUNNING", "SUCCESS", "FAILED", name="syncstatus"),
            nullable=False,
        ),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_metadata")
    # ### end Alembic commands ###
